### ISSUE TITLE
接口数据是模拟的?

### ISSUE THREAD

**Issue by hoosin** [kisnows/react-v2ex#1]

**Comment by kisnows** [comment]
是的，因为前端不能跨域请求 v站的数据，所以是模拟的

**Comment by hoosin** [comment]
关键是没有 api 吧，有 api 的话跨域不是问题，可以用 nginx 或者 nodejs 去转发

**Comment by kisnows** [comment]
@hoosin API是有的，但是我是纯前端环境，也就是一个静态页，所以不能后端转发。
